theme: jekyll-theme-minimal
title: Kaitlyn's first Blog
description: Hello! This is my first blog! My name is Kaitlyn Melton and I am a Biology Major, my hobbies consist of painting and drawing
and I have taken art classes for the past 6 years. I also like soccer and reading, and my favourite subject is Literature/English. 
I am very excited to take this class and learn more.
